import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]
padding = { x = 12, y = 12}
startup_mode = "Maximized"
decorations = "None"
[font]
normal = { family = "JetBrainsMonoNerdFont", style = "SemiBold" }
size = 12
[cursor]
style = { shape = "Beam" }
[env]
TERM = "xterm-256color"
