
[window]
padding = { x = 12, y = 12}
startup_mode = "Maximized"
decorations = "None"
[font]
normal = { family = "JetbrainsMonoNerdFont", style = "SemiBold" }
size = 12
[cursor]
style = { shape = "Beam" }
[env]
TERM = "xterm-256color"
[terminal]
# shell = { program = "/bin/zsh", args = [""] }
[general]
import = [
  "~/.config/alacritty/tokyonight.toml"
]
